### PR TITLE
Added a NoContext widget to the package

### LINKED ISSUE #1: Nice! Can we have a version without context?

### PR DESCRIPTION
**Pull request by Mcpoowl**
No Context widget added which doesn't require a dataview.  Fixes #1

### CODE REVIEW

**Comment by RoelandSalij** [comment]
Thanks Paul!

**Comment by Mcpoowl** [comment]
Glad to be of help @RoelandSalij. Any idea when you get a chance to look at it and merge it if everything is OK?

**Comment by RoelandSalij** [comment]
This week, we'll create a new release and add it to the App Store.

**Comment by Mcpoowl** [comment]
Cool! Let me know if I can help with something!

**Pull request merged**
